ali:
  server:
    host: 47.100.173.161

#eureka:
#  client:
#    service-url:
#      defaultZone: http://${ali.eureka.service.username}:${ali.eureka.service.password}@${ali.eureka.service.host}:${ali.eureka.service.port}/eureka/

server:
  port: 8002

spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: z101496x
    url: jdbc:mysql://${ali.server.host}:3306/spring_cloud_mall?characterEncoding=utf-8&useSSL=false
  jpa:
      show-sql: true  #FIXME
      format-sql: true
#rabbitmq
  rabbitmq:
    username: root
    password: z101496x
    port: 8672
    host: ${ali.server.host}

testmsg: hello11