ali:
  eureka:
    server:
      host: 47.100.173.161
      port: 8761
      username: user
      password: user
eureka:
  client:
    service-url:
      defaultZone: http://${ali.eureka.service.username}:${ali.eureka.service.password}@${ali.eureka.service.host}:${ali.eureka.service.port}/eureka/


spring:
#  application:
#    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: z101496x
    url: jdbc:mysql://${ali-eureka-service-host}:3306/spring_cloud_mall?characterEncoding=utf-8&useSSL=false

testmsg: hello