ali:
  server:
    host: 47.100.173.161
#      port: 8761
#      username: user
#      password: user
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${ali.eureka.service.username}:${ali.eureka.service.password}@${ali.eureka.service.host}:${ali.eureka.service.port}/eureka/
#
server:
  port: 8001

spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${ali.server.host}:3306/spring_cloud_mall?characterEncoding=utf-8&useSSL=false
    username: root
    password: z101496x
  jpa:
    show-sql: true  #FIXME
    format-sql: true
#rabbitmq
  rabbitmq:
    username: guest
    password: guest
    port: 8672
    host: ${ali.service.host}

testmsg: hello