ali:
  server:
    host: 47.100.173.161

#eureka:
#  client:
#    service-url:
#      defaultZone: http://${ali.eureka.service.username}:${ali.eureka.service.password}@${ali.eureka.service.host}:${ali.eureka.service.port}/eureka/

server:
  port: 8003

spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: z101496x
    url: jdbc:mysql://${ali.server.host}:3306/spring_cloud_mall?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 0
    min-idle: 0
    maxActive: 8
    max-wait: 30000
  jpa:
      show-sql: true  #FIXME
      format-sql: true
#rabbitmq
  rabbitmq:
    username: root
    password: z101496x
    port: 8672
    host: ${ali.server.host}
  #redis
  redis:
    host: ${ali.server.host}
    password: z101496x

testmsg: hello11